mode: analyze_cost
techdata_dir: data/tech/posted/
techdata_files:
- Blast Furnace and Basic Oxygen Furnace with CC
- Cement Production
- Coal Gasification
- Direct Air Capture
- Electric Arc Furnace
- Electrolysis
- Fischer-Tropsch
- Haber-Bosch with ASU
- Haber-Bosch with Reforming
- Heatpump for DAC
- Hydrogen Liquefaction
- Hydrogen Storage
- Iron Direct Reduction
- Methanation
- Methane Reforming
- Methanol Synthesis
- Methanol to Gasoline
- Methanol to Kerosene
- Methanol to Olefins
- Steel Casting
- Steel Hot Rolling
- Urea Synthesis
projects_file: config/projects_posted.csv
do_overwrite_project_start_year: true
project_start_year_overwrite: 2025
ccfd_duration: 20
default_wacc: 0.06
show_figures: true
show_figs_in_browser: false
output_dir: output/
save_figures: true
crop_figures: true
scenarios_dir: data/scenarios/basic/
scenarios_actual:
  free_allocations: ''
  prices:
    Electricity: 100 steady
    CO2: PIKExpertGuess-CO2
    Natural Gas: 40 steady
    Hydrogen: PIKExpertGuess-H2
    Coking Coal: 100 steady
    Injection Coal: 70 steady
    Iron Ore: Eisenerz Agora
    Scrap Steel: Zero_Dummy_Scrap
    DRI-Pellets: DRI-Pellets Agora
    Naphta: Naphta a)
